// import "./globals.css";
import type { Metadata } from "next";
import style from "./styles/Layout.module.css";

// for the fonts:
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className={style.main}>{children}</main>
    </>
  );
}
