// import "./globals.css";

import type { Metadata } from "next";
import styles from "./styles/Layout.module.css";
import NavBar from "./components/NavBar/NavBar";
import BlurredCircle from "./components/BlurredCircle/BlurredCircle";

// for the fonts:

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className={styles.layoutWrapper}>
			<div className={styles.navBarWrapper}>
				<NavBar />
			</div>
			<BlurredCircle color="#EF0600" top="-10%" left="10%" />
			<BlurredCircle color="#F7A92E" top="-10" left="60%" />
			<BlurredCircle color="#65B9DE" top="50%" left="50%" />
			<div className={styles.contentWrapper}>{children}</div>
		</div>
	);
}
