// import "./globals.css";

import type { Metadata } from "next";
import styles from "./Layout.module.css";
import NavBar from "./components/NavBar/NavBar";

// for the fonts:

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className={styles.navBarWrapper}>
        <NavBar />
      </div>
      <div className={styles.contentWrapper}>{children}</div>
    </>
  );
}
